"""
Load Structured HTS Codes from JSONL to hts_nodes - Sprint 5.1.5

This script:
1. Reads structured codes from JSONL file (generated by regenerate_structured_hts_codes.py)
2. Upserts them into hts_nodes table
3. Populates duty text for all levels (6, 8, 10-digit)
"""

import sys
import json
import argparse
import asyncio
from pathlib import Path
from typing import List, Dict, Any, Optional
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.core.config import settings
from app.models.hts_node import HTSNode
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def load_jsonl(file_path: Path) -> List[Dict[str, Any]]:
    """Load structured codes from JSONL file."""
    codes = []
    logger.info(f"Loading structured codes from {file_path}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            
            try:
                code_obj = json.loads(line)
                codes.append(code_obj)
            except json.JSONDecodeError as e:
                logger.warning(f"Skipping invalid JSON at line {line_num}: {e}")
                continue
    
    logger.info(f"Loaded {len(codes)} structured codes from JSONL")
    return codes


async def upsert_hts_nodes_batch(
    db: AsyncSession,
    nodes: List[Dict[str, Any]],
    hts_version_id: Optional[str] = None
) -> int:
    """Upsert a batch of HTS nodes."""
    if not nodes:
        return 0
    
    # Prepare values for insert
    values_list = []
    for node in nodes:
        values_list.append({
            "hts_version_id": hts_version_id,
            "code_normalized": node["code_normalized"],
            "code_display": node.get("code_display"),
            "level": node["level"],
            "parent_code_normalized": node.get("parent_code_normalized"),
            "description_short": node.get("description_short"),
            "description_long": node.get("description_long"),
            "duty_general_raw": node.get("duty_general_raw"),
            "duty_special_raw": node.get("duty_special_raw"),
            "duty_column2_raw": node.get("duty_column2_raw"),
            "source_lineage": node.get("source_lineage"),
        })
    
    # Use SQLAlchemy insert with ON CONFLICT
    stmt = pg_insert(HTSNode).values(values_list)
    
    stmt = stmt.on_conflict_do_update(
        index_elements=['hts_version_id', 'level', 'code_normalized'],
        set_={
            "code_display": stmt.excluded.code_display,
            "parent_code_normalized": stmt.excluded.parent_code_normalized,
            "description_short": stmt.excluded.description_short,
            "description_long": stmt.excluded.description_long,
            "duty_general_raw": stmt.excluded.duty_general_raw,
            "duty_special_raw": stmt.excluded.duty_special_raw,
            "duty_column2_raw": stmt.excluded.duty_column2_raw,
            "source_lineage": stmt.excluded.source_lineage,
            "updated_at": text("now()"),
        }
    )
    
    await db.execute(stmt)
    await db.commit()
    
    return len(nodes)


async def load_structured_codes_to_hts_nodes(
    jsonl_path: Path,
    hts_version_id: Optional[str] = None,
    batch_size: int = 1000,
    dry_run: bool = False
):
    """Load structured codes from JSONL into hts_nodes."""
    engine = create_async_engine(settings.DATABASE_URL.replace('postgresql://', 'postgresql+asyncpg://'))
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as db:
        print("=" * 80)
        print("Load Structured HTS Codes to hts_nodes - Sprint 5.1.5")
        print("=" * 80)
        print(f"JSONL File: {jsonl_path}")
        print(f"HTS Version ID: {hts_version_id or 'NULL'}")
        print(f"Batch Size: {batch_size}")
        print(f"Dry Run: {dry_run}")
        print()
        
        # Load JSONL
        if not jsonl_path.exists():
            logger.error(f"❌ JSONL file not found: {jsonl_path}")
            return
        
        codes = load_jsonl(jsonl_path)
        
        if not codes:
            logger.error("❌ No codes loaded from JSONL file")
            return
        
        # Group by level for reporting
        by_level = {}
        for code in codes:
            level = code.get("level", 0)
            by_level[level] = by_level.get(level, 0) + 1
        
        print("Codes by level:")
        for level in sorted(by_level.keys()):
            print(f"  Level {level}: {by_level[level]:,} codes")
        print()
        
        if dry_run:
            print("[DRY RUN] Would upsert:")
            for level in sorted(by_level.keys()):
                print(f"  Level {level}: {by_level[level]:,} nodes")
            return
        
        # Upsert in batches
        total_upserted = 0
        for i in range(0, len(codes), batch_size):
            batch = codes[i:i + batch_size]
            batch_num = i // batch_size + 1
            total_batches = (len(codes) + batch_size - 1) // batch_size
            
            print(f"Processing batch {batch_num}/{total_batches} ({len(batch)} codes)...", end=" ", flush=True)
            
            upserted = await upsert_hts_nodes_batch(db, batch, hts_version_id)
            total_upserted += upserted
            
            print(f"✅ {upserted} nodes upserted")
        
        print(f"\nTotal nodes upserted: {total_upserted:,}")
        
        # Verify final counts
        result = await db.execute(text("""
            SELECT level, COUNT(*) as count
            FROM hts_nodes
            GROUP BY level
            ORDER BY level
        """))
        
        print("\nFinal node counts by level:")
        for row in result:
            print(f"  Level {row[0]}: {row[1]:,} nodes")
        
        # Count nodes with duty text
        result = await db.execute(text("""
            SELECT level, COUNT(*) as count
            FROM hts_nodes
            WHERE duty_general_raw IS NOT NULL
            GROUP BY level
            ORDER BY level
        """))
        
        print("\nNodes with duty_general_raw by level:")
        for row in result:
            print(f"  Level {row[0]}: {row[1]:,} nodes")
    
    await engine.dispose()


def main():
    parser = argparse.ArgumentParser(description="Load structured HTS codes from JSONL to hts_nodes")
    parser.add_argument("--jsonl", type=str, default="data/hts_tariff/structured_hts_codes.jsonl",
                        help="Path to JSONL file with structured codes")
    parser.add_argument("--hts-version-id", type=str, default=None,
                        help="HTS version ID (default: NULL)")
    parser.add_argument("--batch-size", type=int, default=1000,
                        help="Batch size for upserts (default: 1000)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Dry run mode (no database writes)")
    
    args = parser.parse_args()
    
    jsonl_path = Path(args.jsonl)
    if not jsonl_path.is_absolute():
        # Try relative to backend directory
        jsonl_path = Path(__file__).parent.parent.parent / jsonl_path
    
    asyncio.run(load_structured_codes_to_hts_nodes(
        jsonl_path=jsonl_path,
        hts_version_id=args.hts_version_id,
        batch_size=args.batch_size,
        dry_run=args.dry_run
    ))


if __name__ == "__main__":
    main()
